export const tags = [
	{ h_id: "M01", h_text: "목재" },
  { h_id: "M02", h_text: "직물" },
  { h_id: "M03", h_text: "플라스틱" },
  { h_id: "M04", h_text: "가죽" },
  { h_id: "M05", h_text: "세라믹" },
  { h_id: "M06", h_text: "석재" },
  { h_id: "M07", h_text: "종이" },
  { h_id: "M08", h_text: "금속" },
  { h_id: "M09", h_text: "유리" },
  { h_id: "M10", h_text: "고무" },
  { h_id: "M11", h_text: "식료품" },
  { h_id: "M12", h_text: "기타" },
  { h_id: "L01", h_text: "서울" },
  { h_id: "L02", h_text: "경기" },
  { h_id: "L03", h_text: "광주" },
  { h_id: "L04", h_text: "대구" },
  { h_id: "L05", h_text: "대전" },
  { h_id: "L06", h_text: "부산" },
  { h_id: "L07", h_text: "세종" },
  { h_id: "L08", h_text: "울산" },
  { h_id: "L09", h_text: "인천" },
  { h_id: "L10", h_text: "강원" },
  { h_id: "L11", h_text: "경남" },
  { h_id: "L12", h_text: "경북" },
  { h_id: "L13", h_text: "전남" },
  { h_id: "L14", h_text: "전북" },
  { h_id: "L15", h_text: "충남" },
  { h_id: "L16", h_text: "충북" },
  { h_id: "L17", h_text: "제주" },
  { h_id: "G", h_text:"직접"},
  { h_id: "D", h_text:"택배"}
]